### ISSUE TITLE
High RAM and CPU usage

### ISSUE THREAD

**Issue by Ad4mu** [DEVS-MARKET/Desktop-GifDisplay#1]
It takes up too much RAM and CPU.
My PC: Ryzen 5 5600X / 32 GB RAM
![Captura de pantalla 2024-07-30 165404](https://github.com/user-attachments/assets/0594a3aa-96b0-4d3d-bb1a-cb3d74a77bcb)

**Konata**
Default settings: ~2.6 GB
Default, no audio: ~1.3 GB

The same goes for the other GIFs, the lowest it goes is ~800 MB.

Adding `-Xmx1500m` to the Start.bat gets the ~2.6 GB down to ~1 GB, but if I go any lower, it just instantly kills the program.

```
❯ java --version
openjdk 21.0.3 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)
```

**Comment by 0WhiteDev** [comment]
Hey, thanks for report.

I checked my code and found a memory leak, it occurs when loading a gif into an Image object, it is related to a bug for JavaFX with loading gifs.

`Image gifImage = new Image(gifPath.isEmpty() ? Objects.requireNonNull(GifDisplay.class.getResource("/assets/images/" + standardGif.toLowerCase() + ".gif")).toString() : gifPath);`

It is known because a few people have already reported this memory leak on the bugtracker related to jdk, I can't do anything about it, the only solution will be to separate the window and recode it to another graphic lib, I will try to find something optimal and recode it in the nearest free time.

If you have any suggestions, please let me know on discord or in the reply.

**Comment by Ad4mu** [comment]
You totally solved it, now it averages less than 1% CPU usage and 440 MB RAM on default settings, thank you so much <3
